#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/colors.sh

if [ -z "$1" ] || [ -z "$2" ]; then
    echo -en "${COL_RED}usage: ${COL_BLACK}${0##*/} {number-from} {number-to}${COL_RESET}\n"
    echo -en "${COL_BLACK}e.g: ${COL_BLUE}${0##*/} 9 7${COL_RESET}\n\n"
    exit 1;
fi

sed -i -- "s|wlan$1|wlan$2|" ~/.conky/TeejeeTech/Network\ Panel
sed -i -- "s|wlan$1|wlan$2|" ~/.conky/Green\ Apple\ Desktop/conky_seamod
